### ISSUE TITLE
Module 'LineSDKObjC' not found on Xcode Build

### ISSUE THREAD

**Issue by KashiwamochiXR** [line/line-sdk-unity#27]
Enviroment : 
Unity 2019.4.9f1 and 2019.3.15f1(same error)
                      Xcode12.0
                      LineSDK for Unity 1.1.4
                      IOS13.0 and above
                      iPhone11

Discription:
When I build application made by unity with this SDK, I receive this error.
"/Applications/UNITY/Completed/LineLoginTest2/Libraries/Plugins/iOS/LineSDK/LineSDKWrapper.m:29:9: Module 'LineSDKObjC' not found"

on LineSDKWrapper.m 29L.

I found a issue about same error,
https://github.com/line/line-sdk-unity/issues/18
but in this issue,this error seems to be fixed by developer,  ..but I am recieving error now.

what should I do?

**Comment by onevcat** [comment]
Hi,

Installing LINE SDK for Unity requires some environment set up to help the project automatically get the latest version of LINE SDK from GitHub. Please be sure to follow up on the installation guide [here](https://developers.line.biz/zh-hant/docs/unity-sdk/project-setup/#installation-on-ios) and [here](https://developers.line.biz/zh-hant/docs/unity-sdk/integrate-line-login/#getting-the-sdk) to set the project.

If everything is set, do you have any error when exporting your Unity project? It will help us to track down what exactly happens.

And if you are integrating by CocoaPods (which is the default choice), please remember to open the `Unity-iPhone.xcworkspace` instead of the original `Unity-iPhone.xcodeproj` file to build your project. CocoaPods manages the dependencies in the standalone workspace so you will not be able to find the framework in the original project.

Any further information is welcome!

**Comment by KashiwamochiXR** [comment]
omg, I missed CocoaPods requirements.
I will try them. thanks!
