### ISSUE TITLE
Error, unable to process

### ISSUE THREAD

**Issue by Leo199206** [line/line-sdk-unity#40]
Channel Id: 1656533567

The developer platform Android package name has been configured, but you cannot log in. If the code is changed to the package name in the example, you can log in normally, please help determine the reason.

![image](https://user-images.githubusercontent.com/11385515/137267674-2369916e-7439-4d6c-9d2c-481cc9eee777.png)
![image](https://user-images.githubusercontent.com/11385515/137268626-8e9f287c-ee12-4930-90e8-8e56ef729a63.png)

**Comment by Leo199206** [comment]
error message 
![image](https://user-images.githubusercontent.com/11385515/137306316-b9bf84e0-a63b-4169-a461-ea1ee0b1f9d7.png)

**Comment by RainforestPie** [comment]
I encountered the same problem and solved it.
You need to set the status to Published in the Channel (or keep the Developing status and add the specified user as the developer role)
![image](https://user-images.githubusercontent.com/53807655/148209611-4812fc79-daec-4ceb-8bb8-af9b4b03591b.png)

**Comment by onevcat** [comment]
Hi,

Yes, as mentioned above, if a channel is not published yet, only a certain set of users (the account owner and added developers in the Channel Console) can perform the login. So I would suggest your settings in the console.

Since it does not seem like a Unity SDK issue, I am going to close this for now.
